name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  releases:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
      with:
        java-version: 8
        distribution: adopt
    - uses: coursier/cache-action@v6
    - name: Setup GPG
      run: |
        echo "$GPG_PRIVATE_KEY" | gpg --batch --import
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: Publish to Sonatype
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: sbt clean +test +publishSigned sonatypeRelease